"""Adicionando colunas de controle na tabela

Revision ID: 8c6a166030cf
Revises: ffa7b9429c8c
Create Date: 2024-03-01 21:09:42.772986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c6a166030cf'
down_revision: Union[str, None] = 'ffa7b9429c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_pagar_receber', sa.Column('data_baixa', sa.DateTime(), nullable=True))
    op.add_column('contas_a_pagar_receber', sa.Column('valor_baixa', sa.Numeric(), nullable=True))
    op.add_column('contas_a_pagar_receber', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas_a_pagar_receber', 'status')
    op.drop_column('contas_a_pagar_receber', 'valor_baixa')
    op.drop_column('contas_a_pagar_receber', 'data_baixa')
    # ### end Alembic commands ###
